# Generated by Django 2.1.5 on 2019-02-13 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereport',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pagereport',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
