# Generated by Django 2.1.7 on 2019-03-27 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rezq', '0003_user_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.CharField(max_length=253, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Pool ID must NOT be a domain.', regex=re.compile('^(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z0-9-]{2,6}$'))])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pool_enabled',
        ),
        migrations.AddField(
            model_name='resume',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezq.Pool'),
        ),
    ]
